/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp04;

import Business.Business;
import Business.Profiles.FacultyProfile;
import Business.Courses.Course;
import Business.Courses.CourseDirectory;
import Business.Enrollment.Enrollment;
import Business.Enrollment.EnrollmentDirectory;
import Business.StudentProf.StudentProfDirectory;
import Business.StudentProf.StudentProf;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.HashSet;
import javax.swing.JOptionPane;


/**
 *
 * @author Saatvik Gangavarapu
 */
public class ManageStudentProfilesJPanel extends javax.swing.JPanel {
    private JPanel CardSequencePanel;
    private Business business;
    private FacultyProfile facultyProfile;

    private String selectedStudentId;
    private StudentProf selectedExtra;

    /**
     * Creates new form ManageStudentProfilesJPanel
     */
    public ManageStudentProfilesJPanel(Business b, FacultyProfile fp, JPanel jp) {
        initComponents();
        business = b;
        facultyProfile = fp;
        CardSequencePanel = jp;
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnViewUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle1.setText("Faculty - Manage Student Profiles");

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Student", "Hobbies", "Interests", "Academic Progress"
            }
        ));
        tblStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblStudentsMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblStudents);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewUpdate.setText("View/Update");
        btnViewUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(btnViewUpdate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle1)
                    .addComponent(btnBack))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnViewUpdate)
                .addContainerGap(38, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblStudentsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStudentsMousePressed
        // TODO add your handling code here:
        int selectedRow = tblStudents.getSelectionModel().getLeadSelectionIndex();
        if (selectedRow < 0) return;
        selectedStudentId = (String) tblStudents.getValueAt(selectedRow, 0);
        if (selectedStudentId == null) return;
        selectedExtra = business.getStudentProfDirectory().findCreate(selectedStudentId);
        
    }//GEN-LAST:event_tblStudentsMousePressed

    private void btnViewUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUpdateActionPerformed
            // TODO add your handling code here:
        if (selectedExtra == null || selectedStudentId == null) {
            JOptionPane.showMessageDialog(this, "Please select a student");
            return;
        }

        ViewUpdateStudentProfilesJPanel p = new ViewUpdateStudentProfilesJPanel(business, facultyProfile, selectedExtra, CardSequencePanel);

        CardSequencePanel.add("ViewUpdateStudentProfile", p);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

        
    }//GEN-LAST:event_btnViewUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblStudents.getModel();
        model.setRowCount(0);

        String facultyId = facultyProfile.getPerson().getPersonId();

        CourseDirectory cd = business.getCourseDirectory();
        EnrollmentDirectory ed = business.getEnrollmentDirectory();
        StudentProfDirectory sd = business.getStudentProfDirectory();

        HashSet<Course> myCourses = new HashSet<>();
        for (Course c : cd.getCoursesByFaculty(facultyId)) {
            myCourses.add(c);
        }
        
        HashSet<String> studentIds = new HashSet<>();
        for (Course c : myCourses) {
            for (Enrollment e : ed.getEnrollmentByCourse(c)) {
                if (e.getStudent() != null && e.getStudent().getPerson() != null) {
                    studentIds.add(e.getStudent().getPerson().getPersonId());
                }
            }
        }

        for (String sId : studentIds) {
            StudentProf extra = sd.findCreate(sId);

            Object[] row = new Object[4];
            row[0] = sId; 
            row[1] = extra.getHobbies();
            row[2] = extra.getInterests();
            row[3] = extra.getAcademicProgress();

            model.addRow(row);
        }

        selectedStudentId = null;
        selectedExtra = null;
    }   


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTable tblStudents;
    // End of variables declaration//GEN-END:variables
}
