/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole.StudentPanels;

import Business.Business;
import Business.Course;
import Business.Profiles.StudentProfile;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class GraduationAuditJPanel extends javax.swing.JPanel {

    Business business;
    StudentProfile student;
    JPanel CardSequencePanel;

    /**
     * Creates new form GraduationAuditJPanel
     */
    public GraduationAuditJPanel(Business business, StudentProfile student, JPanel CardSequencePanel) {
        initComponents();

        this.business = business;
        this.CardSequencePanel = CardSequencePanel;
        this.student = student;

        populateCompletedCourses();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCompletedCourses = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        txtTotalCreditsEarned = new javax.swing.JTextField();
        txtGraduationStatus = new javax.swing.JTextField();
        btnCreditsEarned = new javax.swing.JButton();
        btnGraduationStatus = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("Graduation Audit");

        tblCompletedCourses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblCompletedCourses);

        btnBack.setText("Back<<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCreditsEarned.setText("Total Credits Earned");
        btnCreditsEarned.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditsEarnedActionPerformed(evt);
            }
        });

        btnGraduationStatus.setText("Graduation Status");
        btnGraduationStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraduationStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(254, 254, 254)
                            .addComponent(lblTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(217, 217, 217)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCreditsEarned)
                                .addComponent(btnGraduationStatus))
                            .addGap(87, 87, 87)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTotalCreditsEarned)
                                .addComponent(txtGraduationStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)))))
                .addContainerGap(261, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCreditsEarned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreditsEarned))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGraduationStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraduationStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnCreditsEarnedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditsEarnedActionPerformed
        // TODO add your handling code here:

        int totalCredits = 0;

        if (student != null && student.getEnrolledCourses() != null) {

            for (Course course : student.getEnrolledCourses()) {

                String grade = course.getGrade();

                if (grade != null && !grade.equals("F")) {
                    totalCredits += course.getCredits();
                }
            }
        }

        txtTotalCreditsEarned.setText(String.valueOf(totalCredits));
    }//GEN-LAST:event_btnCreditsEarnedActionPerformed

    private void btnGraduationStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraduationStatusActionPerformed
        // TODO add your handling code here:

        int totalCredits = 0;

        if (student != null && student.getEnrolledCourses() != null) {

            for (Course course : student.getEnrolledCourses()) {

                String grade = course.getGrade();

                if (grade != null && !grade.equals("F")) {
                    totalCredits += course.getCredits();
                }
            }
        }

        if (totalCredits >= 120) {
            txtGraduationStatus.setText("Eligible for Graduation");
        } else {
            txtGraduationStatus.setText("Not Eligible for Graduation");
        }
    }//GEN-LAST:event_btnGraduationStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreditsEarned;
    private javax.swing.JButton btnGraduationStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCompletedCourses;
    private javax.swing.JTextField txtGraduationStatus;
    private javax.swing.JTextField txtTotalCreditsEarned;
    // End of variables declaration//GEN-END:variables

    private void populateCompletedCourses() {

        DefaultTableModel model = (DefaultTableModel) tblCompletedCourses.getModel();

        model.setRowCount(0);

        model.setColumnIdentifiers(new String[]{
            "Course ID", "Course Name", "Credits", "Grade"
        });

        if (student == null || student.getEnrolledCourses() == null) {
            return;
        }

        for (Course course : student.getEnrolledCourses()) {

            String grade = course.getGrade();

            // Only completed (passed) courses
            if (grade != null && !grade.equals("F")) {

                model.addRow(new Object[]{
                    course.getCourseId(),
                    course.getCourseName(),
                    course.getCredits(),
                    grade
                });
            }
        }
    }
}
