/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * WorkAreaJPanel.java
 *
 * Created on May 17, 2020, 8:35:29 AM
 */
package UserInterface.WorkAreas.AdminRole;

import Business.Business;
import UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp.ManageUserAccountsJPanel;
import UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp.ManagePersonsJPanel;

import javax.swing.JPanel;

/**
 *
 * @author kal
 */
public class AdminRoleWorkAreaJPanel extends javax.swing.JPanel {

    javax.swing.JPanel CardSequencePanel;
    Business business;

    /**
     * Creates new form UnitRiskWorkArea
     */

    public AdminRoleWorkAreaJPanel(Business b, JPanel clp) {

        business = b;
        this.CardSequencePanel = clp;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdministerUserAccounts = new javax.swing.JButton();
        BtnManageFaculty = new javax.swing.JButton();
        btnRegisterPersons = new javax.swing.JButton();
        btnAdminProfile = new javax.swing.JButton();
        btnManageStudents = new javax.swing.JButton();

        setForeground(new java.awt.Color(51, 51, 51));

        btnAdministerUserAccounts.setBackground(new java.awt.Color(102, 153, 255));
        btnAdministerUserAccounts.setFont(getFont());
        btnAdministerUserAccounts.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministerUserAccounts.setText("Administer User Accounts");
        btnAdministerUserAccounts.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdministerUserAccounts.setMaximumSize(new java.awt.Dimension(200, 40));
        btnAdministerUserAccounts.setMinimumSize(new java.awt.Dimension(20, 23));
        btnAdministerUserAccounts.setPreferredSize(new java.awt.Dimension(240, 30));
        btnAdministerUserAccounts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministerUserAccountsIdentifyResourceAssetsActionPerformed(evt);
            }
        });

        BtnManageFaculty.setBackground(new java.awt.Color(102, 153, 255));
        BtnManageFaculty.setFont(getFont());
        BtnManageFaculty.setForeground(new java.awt.Color(255, 255, 255));
        BtnManageFaculty.setText("Manage Faculty");
        BtnManageFaculty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BtnManageFaculty.setMaximumSize(new java.awt.Dimension(200, 40));
        BtnManageFaculty.setMinimumSize(new java.awt.Dimension(20, 20));
        BtnManageFaculty.setPreferredSize(new java.awt.Dimension(240, 25));
        BtnManageFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnManageFacultyActionPerformed(evt);
            }
        });

        btnRegisterPersons.setBackground(new java.awt.Color(102, 153, 255));
        btnRegisterPersons.setFont(getFont());
        btnRegisterPersons.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterPersons.setText("Register  Persons (HR)");
        btnRegisterPersons.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRegisterPersons.setMaximumSize(new java.awt.Dimension(200, 40));
        btnRegisterPersons.setMinimumSize(new java.awt.Dimension(20, 20));
        btnRegisterPersons.setPreferredSize(new java.awt.Dimension(240, 25));
        btnRegisterPersons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPersonsActionPerformed(evt);
            }
        });

        btnAdminProfile.setBackground(new java.awt.Color(102, 153, 255));
        btnAdminProfile.setFont(getFont());
        btnAdminProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminProfile.setText("My Profile");
        btnAdminProfile.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdminProfile.setMaximumSize(new java.awt.Dimension(145, 40));
        btnAdminProfile.setMinimumSize(new java.awt.Dimension(20, 20));
        btnAdminProfile.setPreferredSize(new java.awt.Dimension(240, 25));
        btnAdminProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminProfileIdentifyEventsActionPerformed(evt);
            }
        });

        btnManageStudents.setBackground(new java.awt.Color(102, 153, 255));
        btnManageStudents.setFont(getFont());
        btnManageStudents.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStudents.setText("Manage Students");
        btnManageStudents.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnManageStudents.setMaximumSize(new java.awt.Dimension(200, 40));
        btnManageStudents.setMinimumSize(new java.awt.Dimension(20, 20));
        btnManageStudents.setPreferredSize(new java.awt.Dimension(240, 25));
        btnManageStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdminProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnManageFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdministerUserAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegisterPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(632, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterPersons, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministerUserAccounts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnManageFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnAdminProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministerUserAccountsIdentifyResourceAssetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministerUserAccountsIdentifyResourceAssetsActionPerformed
        // TODO add your handling code here:
        ManageUserAccountsJPanel panel = new ManageUserAccountsJPanel(business, CardSequencePanel);
        CardSequencePanel.add("ManageUserAccounts", panel);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).show(CardSequencePanel, "ManageUserAccounts");
    }//GEN-LAST:event_btnAdministerUserAccountsIdentifyResourceAssetsActionPerformed

    private void btnRegisterPersonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPersonsActionPerformed
        // TODO add your handling code here:

        ManagePersonsJPanel aos = new ManagePersonsJPanel(business, CardSequencePanel);

        CardSequencePanel.add("Manage Persons", aos);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);

    }//GEN-LAST:event_btnRegisterPersonsActionPerformed

    private void btnManageStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentsActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnManageStudentsActionPerformed

    private void btnAdminProfileIdentifyEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminProfileIdentifyEventsActionPerformed
    }//GEN-LAST:event_btnAdminProfileIdentifyEventsActionPerformed

    private void BtnManageFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnManageFacultyActionPerformed
    }//GEN-LAST:event_BtnManageFacultyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnManageFaculty;
    private javax.swing.JButton btnAdminProfile;
    private javax.swing.JButton btnAdministerUserAccounts;
    private javax.swing.JButton btnManageStudents;
    private javax.swing.JButton btnRegisterPersons;
    // End of variables declaration//GEN-END:variables

}
