/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.AdministerUserAccountsWorkResp;

import Business.Business;
import Business.Profiles.Profile;
import Business.UserAccounts.UserAccount;
import Business.UserAccounts.UserAccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *h
 * @author kal bugrara
 */

public class AdminUserAccount extends javax.swing.JPanel {
    
    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;

    UserAccount selecteduseraccount;
    Business business;
    ManageUserAccountsJPanel managePanel;

    public AdminUserAccount(Business business, UserAccount sua, JPanel jp, ManageUserAccountsJPanel managePane) {
        this.CardSequencePanel = jp;
        this.selecteduseraccount = sua;
        this.business = business;
        this.managePanel = managePane;

        initComponents();
        populateFields();
    }
        //display user details here

    private void populateFields() {
        if (selecteduseraccount == null) {
            txtPerson.setText("");
            txtUsername.setText("");
            txtPassword.setText("");
            cmbRole.setSelectedIndex(-1);
            txtPerson.setEditable(true);
            txtUsername.setEditable(true);
            txtPassword.setEditable(true);
            cmbRole.setEnabled(true);
            btnUpdate.setText("Create >>");
            return;
        }
        txtPerson.setText(selecteduseraccount.getPersonId());
        txtUsername.setText(selecteduseraccount.getUserLoginName());
        cmbRole.setSelectedItem(selecteduseraccount.getRole());
        
        txtPassword.setText("");
        txtPerson.setEditable(true);
        cmbRole.setEnabled(true);
        txtUsername.setEditable(true);
        txtPassword.setEditable(true);
        btnUpdate.setText("Update >>");
    }
    private Profile findProfileForRole(String role, String personId) {
        if (role == null || personId == null) return null;

        if (role.equalsIgnoreCase("Admin")) {
            return business.getEmployeeDirectory().findEmployee(personId);
        }
        if (role.equalsIgnoreCase("Student")) {
            return business.getStudentDirectory().findStudent(personId);
        }
        if (role.equalsIgnoreCase("Faculty")) {
            return business.getFacultyDirectory().findFaculty(personId);
        }
        return null;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUpdate = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtPerson = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnUpdate.setText("Update>>");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(480, 290, 100, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Administer User Account");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(40, 290, 100, 23);

        jLabel1.setText("Person");
        add(jLabel1);
        jLabel1.setBounds(150, 110, 50, 17);

        jLabel3.setText("Username");
        add(jLabel3);
        jLabel3.setBounds(140, 180, 80, 20);

        jLabel4.setText("Password");
        add(jLabel4);
        jLabel4.setBounds(140, 220, 80, 17);

        jLabel5.setText("Role");
        add(jLabel5);
        jLabel5.setBounds(170, 150, 30, 17);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword);
        txtPassword.setBounds(250, 220, 130, 23);

        txtPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonActionPerformed(evt);
            }
        });
        add(txtPerson);
        txtPerson.setBounds(250, 100, 130, 23);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername);
        txtUsername.setBounds(250, 180, 130, 23);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Faculty", "Student" }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });
        add(cmbRole);
        cmbRole.setBounds(250, 140, 130, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String personId = txtPerson.getText().trim();
        String username = txtUsername.getText().trim();
        String password = txtPassword.getText().trim();
        String role = (cmbRole.getSelectedItem() == null) ? "" : cmbRole.getSelectedItem().toString();
        
        if (personId.isEmpty() || username.isEmpty() || role.isEmpty()) { JOptionPane.showMessageDialog(this, "Person ID, Username, and Role are required.");
            return;
        }

        Profile profile = findProfileForRole(role, personId);
        if (profile == null) {
            JOptionPane.showMessageDialog(this, "No matching profile found for this Person ID + Role.");
            return;
        }

        UserAccountDirectory uad = business.getUserAccountDirectory();

        if (selecteduseraccount == null) {
            if (password.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Password is required to create a new account.");
                return;
            }
            if (uad.isUsernameTaken(username)) {
                JOptionPane.showMessageDialog(this, "Username already exists.");
                return;
            }

            selecteduseraccount = uad.newUserAccount(profile, username, password); // <-- capture it
            JOptionPane.showMessageDialog(this, "User account created.");

        } else {
            String oldUsername = selecteduseraccount.getUserLoginName();
            boolean usernameChanged = !oldUsername.equalsIgnoreCase(username);

            if (usernameChanged && uad.isUsernameTaken(username)) {
                JOptionPane.showMessageDialog(this, "Username already exists.");
                return;
            }

            selecteduseraccount.setUserLoginName(username);

            if (!password.isEmpty()) {
                selecteduseraccount.setPassword(password);
            }

            JOptionPane.showMessageDialog(this, "User account updated.");
        }

        if (managePanel != null) managePanel.refreshTable();

        CardSequencePanel.remove(this);
        ((CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);

    }//GEN-LAST:event_btnUpdateActionPerformed


    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).previous(CardSequencePanel);


    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRoleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPerson;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
