/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole.FacultyRoleWorkResp01;

import Business.Business;
import Business.Profiles.FacultyProfile;
import Business.Courses.Course;
import Business.Courses.CourseDirectory;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author admin
 */
public class ManageCoursesJPanel extends javax.swing.JPanel {
    
    private JPanel CardSequencePanel;
    private Business business;
    private FacultyProfile facultyProfile;
    private Course selectedCourse;

    /**
     * Creates new form ManageCoursesJPanel
     */
    public ManageCoursesJPanel(Business b, FacultyProfile fp, JPanel jp) {
        initComponents();
        
        business = b;
        facultyProfile = fp;
        CardSequencePanel = jp;
        
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnViewUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCourseTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 153));

        lblTitle.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblTitle.setText("Faculty - Manage Courses");

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewUpdate.setText("View/Update");
        btnViewUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewUpdateActionPerformed(evt);
            }
        });

        tblCourseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course ID", "Course Name", "Credits"
            }
        ));
        tblCourseTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblCourseTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblCourseTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(btnViewUpdate)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addGap(68, 68, 68)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnViewUpdate)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblCourseTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCourseTableMousePressed
        // TODO add your handling code here:
        int selectedrow = tblCourseTable.getSelectionModel().getLeadSelectionIndex();
        if(selectedrow < 0) return;
        
        selectedCourse = (Course)tblCourseTable.getValueAt(selectedrow,0);
        
    }//GEN-LAST:event_tblCourseTableMousePressed

    private void btnViewUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewUpdateActionPerformed
        // TODO add your handling code here:
        if(selectedCourse == null){
            javax.swing.JOptionPane.showMessageDialog(this, "Please Select a Course");
            return;
        }
        
        ViewUpdateCourseJPanel vp = new ViewUpdateCourseJPanel(business, facultyProfile, selectedCourse, CardSequencePanel);
        
        CardSequencePanel.add("ViewCourse", vp);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);
        
        
        
    }//GEN-LAST:event_btnViewUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout)CardSequencePanel.getLayout()).next(CardSequencePanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblCourseTable;
    // End of variables declaration//GEN-END:variables

    private void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) tblCourseTable.getModel();
        
        model.setRowCount(0);
        
        CourseDirectory cd = business.getCourseDirectory();
        
        String facultyId = facultyProfile.getPerson().getPersonId();
        
        for(Course c : cd.getCoursesByFaculty(facultyId)){
            Object row[] = new Object[3];
            
            row[0] = c;
            row[1] = c.getCourseName();
            row[2] = c.getCredits();
            
            model.addRow(row);
        }
    }
}
