/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.WorkAreas.AdminRole.ManagePersonnelWorkResp;

import Business.Business;

import javax.swing.JPanel;

/**
 *
 * @author kal bugrara
 */
public class AdministerPersonJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageSuppliersJPanel
     */
    JPanel CardSequencePanel;

    Business business;

    public AdministerPersonJPanel(Business bz, JPanel jp) {

        CardSequencePanel = jp;
        this.business = bz;
        initComponents();
        updateEmailNuidLabel();
    }

    public void refreshTable() {

    }
    
    private void updateEmailNuidLabel() {
        String role = (cmbRole.getSelectedItem() == null) ? "" : cmbRole.getSelectedItem().toString();
        if ("Student".equalsIgnoreCase(role)) {
            lblEmailNUID.setText("NUID");
        } else {
            lblEmailNUID.setText("Email");
        }    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblEmailNUID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        txtPerson = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        txtEmailNUID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        Back.setText("<< Back");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        add(Back);
        Back.setBounds(30, 290, 80, 23);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Register");
        add(jLabel2);
        jLabel2.setBounds(21, 20, 550, 28);

        jLabel1.setText("Name");
        add(jLabel1);
        jLabel1.setBounds(170, 90, 80, 20);

        lblEmailNUID.setText("Email");
        add(lblEmailNUID);
        lblEmailNUID.setBounds(170, 170, 80, 20);

        jLabel4.setText("Password");
        add(jLabel4);
        jLabel4.setBounds(150, 250, 80, 17);

        jLabel5.setText("Role");
        add(jLabel5);
        jLabel5.setBounds(170, 130, 80, 17);

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        add(txtPassword);
        txtPassword.setBounds(250, 250, 130, 23);

        txtPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonActionPerformed(evt);
            }
        });
        add(txtPerson);
        txtPerson.setBounds(250, 90, 130, 23);

        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        add(txtUsername);
        txtUsername.setBounds(250, 210, 130, 23);

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Faculty", "Student" }));
        cmbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRoleActionPerformed(evt);
            }
        });
        add(cmbRole);
        cmbRole.setBounds(250, 130, 130, 23);

        txtEmailNUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailNUIDActionPerformed(evt);
            }
        });
        add(txtEmailNUID);
        txtEmailNUID.setBounds(250, 170, 130, 23);

        jLabel6.setText("Username");
        add(jLabel6);
        jLabel6.setBounds(150, 210, 80, 20);

        btnUpdate.setText("Update>>");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate);
        btnUpdate.setBounds(480, 290, 100, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        CardSequencePanel.remove(this);
        ((java.awt.CardLayout) CardSequencePanel.getLayout()).next(CardSequencePanel);


    }//GEN-LAST:event_BackActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void cmbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRoleActionPerformed
        // TODO add your handling code here:
        updateEmailNuidLabel();
    }//GEN-LAST:event_cmbRoleActionPerformed

    private void txtEmailNUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailNUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailNUIDActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblEmailNUID;
    private javax.swing.JTextField txtEmailNUID;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPerson;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
